name: Okta Provisioning
on:
  push:

env:
    TF_VAR_api_token: ${{ secrets.OKTA_API_TOKEN }}
    TF_VAR_base_url: ${{ secrets.OKTA_BASE_URL }}
    TF_VAR_org_name: ${{ secrets.OKTA_ORG_NAME }}
    MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_CONFIG_BASE64 }}

jobs:
  terraform-pre-plan-validation:
    name: "Terraform validate (pre-plan)"
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./terraform
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'google-cloud-auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init
      id: init
      run: terraform init -reconfigure

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check  

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

  cnspec-scan-hcl:
    name: "Terraform scan (pre-plan)"
    runs-on: ubuntu-latest
    container: mondoo/cnspec:8
    needs: terraform-pre-plan-validation 

    steps:
      - uses: 'actions/checkout@v3'
      - name: Scan Terraform HCL (pre-plan)
        run: |
          cnspec version
          cnspec status
          cnspec scan terraform ./terraform
        env:
          MONDOO_DETECT_CICD: false
